# Apriori

## Importing the libraries

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=671b783984654480f77ba46332b67d60e11e9396ce5d1642f34b4554d8997dad
  Stored in directory: /root/.cache/pip/wheels/77/3d/a6/d317a6fb32be58a602b1e8c6b5d6f31f79322da554cad2a5ea
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as py

## Data Preprocessing

In [ ]:
dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None) # there is no column names so no headers in the file
transactions = []
for i in range(0, 7051):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])

## Training the Apriori model on the dataset

In [28]:
from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

## Visualising the results

### Displaying the first results coming directly from the output of the apriori function

In [29]:
results = list(rules)

In [30]:
print(results)

[RelationRecord(items=frozenset({'burgers', 'almonds'}), support=0.005531130336122536, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.2671232876712329, lift=3.102942835864684)]), RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004396539497943554, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.28703703703703703, lift=4.73980830948044)]), RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005814778045667281, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30597014925373134, lift=3.8593837609804287)]), RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.00524748262657779, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3737373737373737, lift=4.714172132776784)]), RelationRecord(items=frozenset({'honey', 'fromage blanc'}), support=0.0035455963693093178, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.27777777777777773, lift=5.726933073424301)]), RelationRecord(items=frozenset({'frozen vegetables', 'parmesan cheese'}), support=0.005389306481350163, ordered_statistics=[OrderedStatistic(items_base=frozenset({'parmesan cheese'}), items_add=frozenset({'frozen vegetables'}), confidence=0.2900763358778626, lift=3.048179201601802)]), RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.015742447879733373, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3226744186046512, lift=3.2689329390537294)]), RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.00524748262657779, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3737373737373737, lift=3.786238825031928)]), RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.0032619486597645726, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.21296296296296297, lift=3.222321570497536)]), RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007658488157708127, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2621359223300971, lift=3.9663527646985286)]), RelationRecord(items=frozenset({'shrimp', 'pasta'}), support=0.0035455963693093178, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.2525252525252525, lift=3.491285403050108)])]

### Putting the results well organised into a Pandas DataFrame

In [31]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

### Displaying the results non sorted

In [32]:
resultsinDataFrame

          Left Hand Side    Right Hand Side   Support  Confidence      Lift
0                almonds            burgers  0.005531    0.267123  3.102943
1            light cream            chicken  0.004397    0.287037  4.739808
2   mushroom cream sauce           escalope  0.005815    0.305970  3.859384
3                  pasta           escalope  0.005247    0.373737  4.714172
4          fromage blanc              honey  0.003546    0.277778  5.726933
5        parmesan cheese  frozen vegetables  0.005389    0.290076  3.048179
6          herb & pepper        ground beef  0.015742    0.322674  3.268933
7           tomato sauce        ground beef  0.005247    0.373737  3.786239
8            light cream          olive oil  0.003262    0.212963  3.222322
9      whole wheat pasta          olive oil  0.007658    0.262136  3.966353
10                 pasta             shrimp  0.003546    0.252525  3.491285

### Displaying the results sorted by descending lifts

In [36]:
resultsinDataFrame.nlargest(n = 10, columns = 'Lift')

          Left Hand Side Right Hand Side   Support  Confidence      Lift
4          fromage blanc           honey  0.003546    0.277778  5.726933
1            light cream         chicken  0.004397    0.287037  4.739808
3                  pasta        escalope  0.005247    0.373737  4.714172
9      whole wheat pasta       olive oil  0.007658    0.262136  3.966353
2   mushroom cream sauce        escalope  0.005815    0.305970  3.859384
7           tomato sauce     ground beef  0.005247    0.373737  3.786239
10                 pasta          shrimp  0.003546    0.252525  3.491285
6          herb & pepper     ground beef  0.015742    0.322674  3.268933
8            light cream       olive oil  0.003262    0.212963  3.222322
0                almonds         burgers  0.005531    0.267123  3.102943